#include <initializer_list>
#include <iostream>
#include <iterator>
#include <memory>
#include <sstream> // __str__
#include <string>
#include <vector>

#include <pybind11/pybind11.h>

#ifndef BINDER_PYBIND11_TYPE_CASTER
	#define BINDER_PYBIND11_TYPE_CASTER
	PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
	PYBIND11_DECLARE_HOLDER_TYPE(T, T*);
	PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>);
#endif

void bind_std_stl_vector_4(std::function< pybind11::module &(std::string const &namespace_) > &M)
{
	std::cout << "B12_[std::vector<mmtf::BioAssembly>] ";
	{ // std::vector file:bits/stl_vector.h line:216
		pybind11::class_<std::vector<mmtf::BioAssembly>, std::shared_ptr<std::vector<mmtf::BioAssembly>>> cl(M("std"), "vector_mmtf_BioAssembly_t", "");
		pybind11::handle cl_type = cl;

		cl.def( pybind11::init( [](){ return new std::vector<mmtf::BioAssembly>(); } ) );
		cl.def( pybind11::init<const class std::allocator<struct mmtf::BioAssembly> &>(), pybind11::arg("__a") );

		cl.def( pybind11::init( [](unsigned long const & a0){ return new std::vector<mmtf::BioAssembly>(a0); } ), "doc");
		cl.def( pybind11::init<unsigned long, const class std::allocator<struct mmtf::BioAssembly> &>(), pybind11::arg("__n"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](unsigned long const & a0, const struct mmtf::BioAssembly & a1){ return new std::vector<mmtf::BioAssembly>(a0, a1); } ), "doc");
		cl.def( pybind11::init<unsigned long, const struct mmtf::BioAssembly &, const class std::allocator<struct mmtf::BioAssembly> &>(), pybind11::arg("__n"), pybind11::arg("__value"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](std::vector<mmtf::BioAssembly> const &o){ return new std::vector<mmtf::BioAssembly>(o); } ) );
		cl.def( pybind11::init<const class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > &, const class std::allocator<struct mmtf::BioAssembly> &>(), pybind11::arg("__x"), pybind11::arg("__a") );

		cl.def( pybind11::init( [](class std::initializer_list<struct mmtf::BioAssembly> const & a0){ return new std::vector<mmtf::BioAssembly>(a0); } ), "doc");
		cl.def( pybind11::init<class std::initializer_list<struct mmtf::BioAssembly>, const class std::allocator<struct mmtf::BioAssembly> &>(), pybind11::arg("__l"), pybind11::arg("__a") );

		cl.def("get_allocator", [](std::vector<mmtf::BioAssembly> const &o) -> std::allocator<struct mmtf::BioAssembly> { return o.get_allocator(); }, "");
		cl.def("assign", (class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > & (std::vector<mmtf::BioAssembly>::*)(const class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > &)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::operator=, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::operator=(const class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > &) --> class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > &", pybind11::return_value_policy::automatic, pybind11::arg("__x"));
		cl.def("assign", (class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > & (std::vector<mmtf::BioAssembly>::*)(class std::initializer_list<struct mmtf::BioAssembly>)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::operator=, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::operator=(class std::initializer_list<struct mmtf::BioAssembly>) --> class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > &", pybind11::return_value_policy::automatic, pybind11::arg("__l"));
		cl.def("assign", (void (std::vector<mmtf::BioAssembly>::*)(unsigned long, const struct mmtf::BioAssembly &)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::assign, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::assign(unsigned long, const struct mmtf::BioAssembly &) --> void", pybind11::arg("__n"), pybind11::arg("__val"));
		cl.def("assign", (void (std::vector<mmtf::BioAssembly>::*)(class std::initializer_list<struct mmtf::BioAssembly>)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::assign, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::assign(class std::initializer_list<struct mmtf::BioAssembly>) --> void", pybind11::arg("__l"));
		cl.def("begin", (class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)()) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::begin, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::begin() --> class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >");
		cl.def("end", (class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)()) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::end, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::end() --> class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >");
		cl.def("cbegin", (class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)() const) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::cbegin, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::cbegin() const --> class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >");
		cl.def("cend", (class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)() const) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::cend, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::cend() const --> class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >");
		cl.def("size", (unsigned long (std::vector<mmtf::BioAssembly>::*)() const) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::size, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::size() const --> unsigned long");
		cl.def("max_size", (unsigned long (std::vector<mmtf::BioAssembly>::*)() const) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::max_size, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::max_size() const --> unsigned long");
		cl.def("resize", (void (std::vector<mmtf::BioAssembly>::*)(unsigned long)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::resize, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::resize(unsigned long) --> void", pybind11::arg("__new_size"));
		cl.def("resize", (void (std::vector<mmtf::BioAssembly>::*)(unsigned long, const struct mmtf::BioAssembly &)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::resize, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::resize(unsigned long, const struct mmtf::BioAssembly &) --> void", pybind11::arg("__new_size"), pybind11::arg("__x"));
		cl.def("shrink_to_fit", (void (std::vector<mmtf::BioAssembly>::*)()) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::shrink_to_fit, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::shrink_to_fit() --> void");
		cl.def("capacity", (unsigned long (std::vector<mmtf::BioAssembly>::*)() const) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::capacity, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::capacity() const --> unsigned long");
		cl.def("empty", (bool (std::vector<mmtf::BioAssembly>::*)() const) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::empty, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::empty() const --> bool");
		cl.def("reserve", (void (std::vector<mmtf::BioAssembly>::*)(unsigned long)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::reserve, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::reserve(unsigned long) --> void", pybind11::arg("__n"));
		cl.def("__getitem__", (struct mmtf::BioAssembly & (std::vector<mmtf::BioAssembly>::*)(unsigned long)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::operator[], "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::operator[](unsigned long) --> struct mmtf::BioAssembly &", pybind11::return_value_policy::automatic, pybind11::arg("__n"));
		cl.def("at", (struct mmtf::BioAssembly & (std::vector<mmtf::BioAssembly>::*)(unsigned long)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::at, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::at(unsigned long) --> struct mmtf::BioAssembly &", pybind11::return_value_policy::automatic, pybind11::arg("__n"));
		cl.def("front", (struct mmtf::BioAssembly & (std::vector<mmtf::BioAssembly>::*)()) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::front, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::front() --> struct mmtf::BioAssembly &", pybind11::return_value_policy::automatic);
		cl.def("back", (struct mmtf::BioAssembly & (std::vector<mmtf::BioAssembly>::*)()) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::back, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::back() --> struct mmtf::BioAssembly &", pybind11::return_value_policy::automatic);
		cl.def("data", (struct mmtf::BioAssembly * (std::vector<mmtf::BioAssembly>::*)()) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::data, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::data() --> struct mmtf::BioAssembly *", pybind11::return_value_policy::automatic);
		cl.def("push_back", (void (std::vector<mmtf::BioAssembly>::*)(const struct mmtf::BioAssembly &)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::push_back, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::push_back(const struct mmtf::BioAssembly &) --> void", pybind11::arg("__x"));
		cl.def("pop_back", (void (std::vector<mmtf::BioAssembly>::*)()) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::pop_back, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::pop_back() --> void");
		cl.def("insert", (class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >, const struct mmtf::BioAssembly &)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::insert, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::insert(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >, const struct mmtf::BioAssembly &) --> class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >", pybind11::arg("__position"), pybind11::arg("__x"));
		cl.def("insert", (class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >, class std::initializer_list<struct mmtf::BioAssembly>)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::insert, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::insert(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >, class std::initializer_list<struct mmtf::BioAssembly>) --> class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >", pybind11::arg("__position"), pybind11::arg("__l"));
		cl.def("insert", (class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >, unsigned long, const struct mmtf::BioAssembly &)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::insert, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::insert(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >, unsigned long, const struct mmtf::BioAssembly &) --> class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >", pybind11::arg("__position"), pybind11::arg("__n"), pybind11::arg("__x"));
		cl.def("erase", (class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::erase, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::erase(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >) --> class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >", pybind11::arg("__position"));
		cl.def("erase", (class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > > (std::vector<mmtf::BioAssembly>::*)(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >, class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::erase, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::erase(class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >, class __gnu_cxx::__normal_iterator<const struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >) --> class __gnu_cxx::__normal_iterator<struct mmtf::BioAssembly *, class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > >", pybind11::arg("__first"), pybind11::arg("__last"));
		cl.def("swap", (void (std::vector<mmtf::BioAssembly>::*)(class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > &)) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::swap, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::swap(class std::vector<struct mmtf::BioAssembly, class std::allocator<struct mmtf::BioAssembly> > &) --> void", pybind11::arg("__x"));
		cl.def("clear", (void (std::vector<mmtf::BioAssembly>::*)()) &std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::clear, "C++: std::vector<mmtf::BioAssembly, std::allocator<mmtf::BioAssembly> >::clear() --> void");
	}
}
